apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  members:
    # a list of projects joined into the service mesh
    - bookinfo
    - recommendation